[2023-09-06T15:35:50.905+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-06T15:35:50.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-06T15:35:50.912+0000] {taskinstance.py:1361} INFO - Starting attempt 16 of 16
[2023-09-06T15:35:50.920+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ingest> on 2023-01-01 00:00:00+00:00
[2023-09-06T15:35:50.924+0000] {standard_task_runner.py:57} INFO - Started process 589 to run task
[2023-09-06T15:35:50.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_ingestion_dag', 'ingest', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_localdb_dag.py', '--cfg-path', '/tmp/tmpflvfqicp']
[2023-09-06T15:35:50.931+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask ingest
[2023-09-06T15:35:50.971+0000] {task_command.py:415} INFO - Running <TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [running]> on host 8c255a8714b1
[2023-09-06T15:35:51.002+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-06T15:35:51.251+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2023-09-06T15:35:51.252+0000] {logging_mixin.py:151} INFO - yellow_taxi_2023_01 /opt/***/output_2023-01.parquet 2023-01
[2023-09-06T15:35:51.267+0000] {logging_mixin.py:151} INFO - connection established successfully, inserting data...
[2023-09-06T15:35:51.298+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 18, in ingest_callable
    df_iter = pd.read_parquet(parquet_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 227, in read
    pa_table = self.api.parquet.read_table(
TypeError: read_table() got an unexpected keyword argument 'iterator'
[2023-09-06T15:35:51.307+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=local_ingestion_dag, task_id=ingest, execution_date=20230101T000000, start_date=20230906T153550, end_date=20230906T153551
[2023-09-06T15:35:51.313+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task ingest (read_table() got an unexpected keyword argument 'iterator'; 589)
[2023-09-06T15:35:51.346+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T15:35:51.362+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
